module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.cuisine = [
    'Mexican',
    'Chinese',
    'SteakHouse',
    'Vietamese',
    'Fast Food',
    'Vietamese',
    'Pizza',
    'Vietamese',
    'Vietamese',
    'Mexican',
    'Fast Food',
    'Pizza',
    'Chinese',
    'Pizza',
    'Pizza',
    'Mexican',
    'Chinese',
    'SteakHouse',
    'Vietamese',
    'Fast Food',
    'Vietamese',
    'Pizza'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]
